version: '3.7'

services:
  onf-server:
    container_name: ONF-server
    image: reg.brian-hong.tech/ONF/ONF-server:latest
    platform: linux/arm64/v8
    restart: unless-stopped
    ports:
      - 6060:3000
    env_file:
      - ./.env
    networks:
      - ONF-network

  onf-redis:
    container_name: ONF-redis
    image: redis:latest
    ports:
      - 6379:6379
    env_file:
      - ./.env
    networks:
      - ONF-network

networks:
  ONF-network:
